# Generated by Django 6.0.2 on 2026-03-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titletemplate',
            name='template_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='titletemplate',
            name='docx_template_file',
            field=models.FileField(blank=True, null=True, upload_to='title_templates/'),
        ),
    ]
