# Generated by Django 6.0.2 on 2026-03-13 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleDocumentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(default='TITLE', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_docx', models.FileField(blank=True, null=True, upload_to='title_jobs/output/')),
                ('output_pdf', models.FileField(blank=True, null=True, upload_to='title_jobs/output/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True)),
            ],
        ),
    ]
